# docker-compose.dev.yml
version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: xonebot_postgres_dev
    environment:
      - POSTGRES_DB=xonebot_dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: xonebot_redis_dev
    ports:
      - "6379:6379"
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: xonebot_qdrant_dev
    ports:
      - "6333:6333" # API port
      - "6334:6334" # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data: